sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t whideaevolver/playground-docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true whideaevolver/playground-docker-react-test npm test

after_success:
  - docker build -t whideaevolver/multi-client ./client
  - docker build -t whideaevolver/multi-nginx ./nginx
  - docker build -t whideaevolver/multi-server ./server
  - docker build -t whideaevolver/multi-worker ./worker
  # Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push whideaevolver/multi-client
  - docker push whideaevolver/multi-nginx
  - docker push whideaevolver/multi-server
  - docker push whideaevolver/multi-worker
